version: 2.1
workflows:
  builds:
    jobs:
      - build

jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
       - run:
          name: Show storage prefix
          command: cat /.circleci-runner-config.json  | jq .Dispatched.TaskInfo.Storage
       - run: echo "foo" > test.txt
       - save_cache:
           key: foo
           paths:
             - ./test.txt
       - restore_cache:
          keys:
            - foo
